language: java

jdk:
        - oraclejdk8

addons:
  sonarcloud:
    organization: "felixreimann" # the key of the org you chose at step #3
script:
  - sonar-scanner

after_success:
- ./gradlew jacocoTestReport coveralls
